### PR TITLE
Changed 'add_remote' to 'add-remote' to match naming conventions

### PR DESCRIPTION
**Pull request by FredAmartey**

### CODE REVIEW

**Comment by sauravchirania** [comment]
Hey @FredAmartey,

Thanks for the patch. However, it just updates the README file. We also have to update the actual command itself. Moreover, when sending a change, it is generally considered good to mention the bug id (in this case #23) so that the reviewers can easily get the context of your PR.

**Comment by nurdtechie98** [comment]
@FredAmartey , apart from things said by @sauravchirania  all the pull requests needs to be made to dev branch not the master

**Comment by FredAmartey** [comment]
I'm sorry about that. I'm new to making contributions and I didn't know a lot of these things. Is there anyway I can correct what I've done or what should I do instead?

**Comment by nurdtechie98** [comment]
No worries @FredAmartey. Step one make the changes to code as explained by @sauravchirania then once done create a new pull request with base as nurdtechie98/drive-cli dev branch from your naming issue branch, thats it.

**Comment by FredAmartey** [comment]
@nurdtechie98 The only 'dev' branches I see are 'origin/dev' and 'upstream/dev' is there something I'm missing?

**Pull request closed without merging**
