### PR TITLE
Updated Readme

### LINKED ISSUE #28: Typo in Readme
[status: list changes made to local files since last pull or pull.
](https://github.com/nurdtechie98/drive-cli#features)
I guess it should be last push or pull

### PR DESCRIPTION
**Pull request by Avni-Sharma**
Fixes #28

### CODE REVIEW

**Comment by inishchith** [comment]
@Avni-Sharma Thanks for the PR. Can you please remove the changes which aren't related to the issue?

**Comment by Avni-Sharma** [comment]
How shall I remove the previous commits. I am also working for the error handling issue, so it seems that it has also appeared here

**Comment by inishchith** [comment]
Okay. Not a problem.
For now you can follow - 
1. Create a new branch
> git branch -b <branch_name>
2. Revert to previous commit of origin
> git log 
- select commit which you didn't do
> git reset ---hard <commit_hash>
3. fetch updates from this repository
> git fetch --all
> git reset --hard upstream/master
- note : `upstream` in this case is this repository's remote url
4. Make changes , commit & push

**Comment by Avni-Sharma** [comment]
Hi there, I tried the above steps but it seems it is not working. Shall I rebase my master and checkout from there?

**Pull request closed without merging**
